name: vaapi-test
base: core22
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test PoC snap for Proto's VAAPI solution
description: |
  Test PoC snap for Proto's VAAPI solution

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  gst-inspect:
    command: /usr/bin/gst-inspect-1.0
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
  vainfo:
    command: /usr/bin/vainfo
    environment:
      LIBVA_DRIVERS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri

parts:
  gmmlib:
    source: https://github.com/intel/gmmlib.git
    source-branch: master
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-stage: |
      craftctl default

      # patch the generated .pc file to correct 'installdir' and 'libdir'
      sed -i -e "s@/usr/include@/root/stage/usr/include@" "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig/igdgmm.pc"
      sed -i -e "s@/usr/lib/@/root/stage/usr/lib@" "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig/igdgmm.pc"

  libva:
    source: https://github.com/intel/libva.git
    source-branch: master
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libwayland-dev
      - meson
      - ninja-build

  libva-utils:
    after: [ libva ]
    source: https://github.com/intel/libva-utils.git
    source-branch: master
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - pkg-config

  ihd-vaapi-driver:
    after: [ gmmlib, libva ]
    source: https://github.com/intel/media-driver
    source-type: git
    source-branch: master
    plugin: cmake
    build-packages:
      - pkg-config

  mesa-core22:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      #  This package depends on the full suite of drivers for the Video Acceleration
      # API (VA API). It does not provide any drivers itself, and may be removed if
      # you wish to only have certain drivers installed.
      - va-driver-all
      - libegl1
      - libgles2
    stage:
      # filter libva* as it's being built from
      # source (see above)
      - -usr/lib/x86_64-linux-gnu/libva.so.2*
      - -usr/lib/x86_64-linux-gnu/libigdgmm.so.12*
      - -usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so

# QUESTION -- how does this part find libva????
# Does snapcraft automagically handle the pkg-config?
  gstreamer:
    after: [ ihd-vaapi-driver ]
    source: https://github.com/GStreamer/gstreamer.git
    source-tag: 1.20.5
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=debugoptimized
      - -Dintrospection=enabled
      - -Dvaapi=enabled
      - -Dgstreamer-vaapi:with_wayland=yes
      - -Dgstreamer-vaapi:with_x11=yes
      - -Dorc=enabled
      - -Dgst-plugins-base:pango=enabled
      - -Dgst-plugins-base:gl_winsys=wayland
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dbad=enabled
      - -Dgst-plugins-bad:tests=disabled
      - -Dugly=disabled
      - -Ddevtools=enabled
      - -Dlibnice=enabled
      - -Dlibav=disabled
#   build-environment:
#     PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig/
# Note - the default gstreamer build builds a number of optional
# dependencies, including FFmpeg. Ideally this should be disabled
# and the snap modified to use ffmpeg from the archive.
#
#      - -DFFmpeg=disabled     this doesn't work!
    build-packages:
      - bison
      - flex
#       required by gst-base:opengl plugin
      - libgraphene-1.0-dev
#       required by gst-base:ogg
      - libogg-dev
#       required by gst-base:opus
      - libopus-dev
#       required by gst-plugins-good
      - libmp3lame-dev
      - libdv-dev
      - libpsl-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libvorbis-dev
#     - libnice-dev resuls in all of these extra dependencies:
#  gir1.2-gssdp-1.2 gir1.2-gupnp-1.2 gir1.2-gupnpigd-1.0 gir1.2-nice-0.1 libgmp-dev libgmpxx4ldbl libgnutls-dane0 libgnutls28-dev libgnutlsxx28 libgssdp-1.2-dev libgupnp-1.2-dev
#  libgupnp-igd-1.0-dev libidn2-dev libp11-kit-dev libtasn1-6-dev libtasn1-doc libunbound8 nettle-dev
#
#     gst-plugins-bad
#     - libavtp-dev			doesn't exist in ubuntu??? WTF
#     - fdk-aac???
#     - libmicrodns
      - libopenh264-dev
      - libdrm-dev
      - libgirepository1.0-dev
      - libssl-dev
      - libudev-dev
      - libunwind-dev
      - libwayland-dev
      - libegl-dev
      - pkg-config
      - waylandpp-dev
    stage-packages:
      - libdv4
      - libmp3lame0
      - libxext6
      - libaom3
      - libasound2
      - libass9
#     TODO: there are multiple packages which provide this library; REVIEW
      - libblas3
#     FIXME: determine how to remove this dependency if possible using meson.
      - libbluray2
      - libbs2b0
      - libchromaprint1
      - libcodec2-1.0
      - libdav1d5
      - libflite1
      - libgdk-pixbuf-2.0-0
      - libgfortran5
      - libgme0
      - libgomp1
      - libgsm1
      - libjpeg-turbo8
      - liblapack3
      - liblilv-0-0
      - libmfx1
      - libmpg123-0
      - libmysofa1
      - libnorm1
      - libnuma1
      - libogg0
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libpgm-5.3-0
      - libpocketsphinx3
      - libquadmath0
      - librabbitmq4
      - librsvg2-2
      - librubberband2
      - libsamplerate0
      - libserd-0-0
      - libshine3
      - libsnappy1v5
      - libsodium23
      - libsord-0-0
      - libsoxr0
      - libspeex1
      - libsphinxbase3
      - libsratom-0-0
      - libsrt1.4-gnutls
      - libssh-gcrypt-4
      - libtheora0
      - libtwolame0
      - libudfread0
      - libvdpau1
      - libvidstab1.1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx7
      - libwebp7
      - libwebpmux3
      - libx264-163
      - libx265-199
      - libxvidcore4
      - libzimg2
      - libzmq5
      - libzvbi0
      - libwayland-cursor0
      - libwayland-egl1
      - libgraphene-1.0-0
      - libopenh264-6
      - libunwind8
      - libxml2
      - ocl-icd-libopencl1
    stage:
      - -usr/lib/x86_64-linux-gnu/libva*

