name: vaapi-test
base: core22
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test PoC snap for Proto's VAAPI solution
description: |
  Test PoC snap for Proto's VAAPI solution

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  gst-inspect:
    command: /usr/bin/gst-inspect-1.0
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
  vainfo:
    command: /usr/bin/vainfo
    environment:
      LIBVA_DRIVERS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri

parts:
  gmmlib:
    source: https://github.com/intel/gmmlib.git
    source-branch: master
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-stage: |
      craftctl default

      # patch the generated .pc file to correct 'installdir' and 'libdir'
      sed -i -e "s@/usr/include@/root/stage/usr/include@" "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig/igdgmm.pc"
      sed -i -e "s@/usr/lib/@/root/stage/usr/lib@" "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig/igdgmm.pc"

  libva:
    source: https://github.com/intel/libva.git
    source-branch: master
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libwayland-dev
      - meson
      - ninja-build

  libva-utils:
    after: [ libva ]
    source: https://github.com/intel/libva-utils.git
    source-branch: master
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - pkg-config

  ihd-vaapi-driver:
    after: [ gmmlib, libva ]
    source: https://github.com/intel/media-driver
    source-type: git
    source-branch: master
    plugin: cmake
    build-packages:
      - pkg-config

  mesa-core22:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      #  This package depends on the full suite of drivers for the Video Acceleration
      # API (VA API). It does not provide any drivers itself, and may be removed if
      # you wish to only have certain drivers installed.
      - va-driver-all
      - libegl1
      - libgles2
    stage:
      # filter libva* as it's being built from
      # source (see above)
      - -usr/lib/x86_64-linux-gnu/libva.so.2*
      - -usr/lib/x86_64-linux-gnu/libigdgmm.so.12*
      - -usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so

  gstreamer:
    after: [ ihd-vaapi-driver ]
    source: https://github.com/GStreamer/gstreamer.git
    source-tag: 1.20.5
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=debugoptimized
      - -Dintrospection=enabled
      - -Dvaapi=enabled
      - -Dorc=enabled
      - -Dgst-plugins-base:pango=enabled
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dbad=enabled
      - -Dugly=disabled
      - -Ddevtools=enabled
      - -Dlibnice=enabled
      - -Dlibav=enabled
      - -Dgstreamer-vaapi:with_drm=yes
# Note - the default gstreamer build builds a number of optional
# dependencies, including FFmpeg. Ideally this should be disabled
# and the snap modified to use ffmpeg from the archive.
#
#      - -DFFmpeg=disabled     this doesn't work!
    build-packages:
      - bison
      - flex
      - libavcodec-dev
      - libdrm-dev
      - libgirepository1.0-dev
      - libssl-dev
      - libudev-dev
      - libunwind-dev
      - libwayland-dev
      - pkg-config
      - waylandpp-dev
    stage-packages:
      - libunwind8
      - libxml2
